### ISSUE TITLE
New versions of asterisk please

### ISSUE THREAD

**Issue by pablodz** [andrius/asterisk#19]
Hello there,

please release the new versions of Asterisk :)

**Comment by mikegleasonjr** [comment]
👍🏻 🙏🏻

**Comment by nospoon** [comment]
Based on the fact that the repo still uses ancient debian and asterisk version I'm assuming it's been abandoned.

**Comment by mikegleasonjr** [comment]
I built the latest version here: https://hub.docker.com/r/mikegleasonjr/asterisk

**Comment by andrius** [comment]
partially resolved ;)
