### ISSUE TITLE
configuration

### ISSUE THREAD

**Issue by sovanc** [andrius/asterisk#3]
Andrius,

Cool project you have here.  I got the image to work. How do I add sip support?  Also, I'm trying to get into bash so I modify sip.conf and extensions.conf.  I can't connect via docker exec.  Not sure if there's a better way.

**Comment by AlessandroMinoccheri** [comment]
If you want to enter into the docker you need to launch:

```
docker exec -it {CONTAINER} sh 
```

to add sip support you can create a sip.conf and inside your Dockerfile or docker-compose you can get the file and paste into the docker image in the right location

**Comment by sovanc** [comment]
Thanks for your kind reply.  

I have an AWS SnowballEdge and would like to install Asterisk on one of the Compute instances.  The installation works and my two soft phones are registered successfully.  When I made the call, the phone rings, but no audio.  After awhile, the call drops.  

SnowballEdge has an internal IP which is not routeable.  From my laptop, I use an associated ip address that got mapped to the internal IP of the Snowballedge.  

sip show peers -- everything looks good.

wireshark trace shows Destination unreachable (Host administratively prohibited)
DSCP: Unknown
Differentiated Services Codepoint: Unknown (5)

I can ping and ssh to the Compute instance in the SnowballEdge.  

This is not an Asterisk problem.  I was wondering if you can offer some recommendations here.

**Comment by SagaBeogradGitHub** [comment]
as i can see from the configuation , the rtp port mapping is not done. So basically you need to define a port range in asterisk rtp.conf configuration and map this port range when starting a container

Hope this helps

**Comment by andrius** [comment]
You could use --net=host or configure your asterisk properly (map SIP and RTP ports). Basically, your asterisk in docker are behind NAT, hope this helps: https://andrius.mobi/2018/12/digital-ocean-floating-ip-and-voip.html

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
