### ISSUE TITLE
add sngrep

### ISSUE THREAD

**Issue by felipem1210** [andrius/asterisk#6]
Hi andrius

It would be great if you add the installation of sngrep in all the images you maintain. This is a popular tool for SIP debugging.

Thanks in advance

**Comment by andrius** [comment]
Hi, you could simply use this docker image as a barebone for your dockerfile; people do have various needs and this will increase the size of image. But I'll think about sngrep support.

There is also my own [sngrep image](https://hub.docker.com/r/andrius/alpine-sngrep) at docker hub and by using  docker container networking you could easily chain sngrep/asterisk together
